/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_serialport_SerialPort */

#ifndef _Included_serialport_amos_cem_com_libamosserial_SerialPort
#define _Included_serialport_amos_cem_com_libamosserial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     serialport_amos_cem_com_libamosserial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_serialport_amos_cem_com_libamosserial_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     serialport_amos_cem_com_libamosserial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_serialport_amos_cem_com_libamosserial_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
